# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
# name: "Label PRs from globs"
# on:
#   schedule:
#   - cron: "0 * * * *"

# jobs:
#   execute:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: jpmcb/prow-github-actions@v1.1.1
#         with:
#           jobs: 'pr-labeler'
#           github-token: "${{ secrets.GITHUB_TOKEN }}"

name: Project / Pull Request Labeler

on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, reopened, edited]

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    # - name: Monitor Actions
    #   uses: GitHubSecurityLab/actions-permissions/monitor@37c927c24552caa0ef6040ab0876db729cc12754 # v1.0.2
    #   with:
    #     config: ${{ vars.PERMISSIONS_CONFIG }}
    - uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7.0.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
