# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
name: Project / Size PR

on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]

jobs:
  update_labels:
    runs-on: ubuntu-latest
    steps:
    - name: Monitor Actions
      uses: GitHubSecurityLab/actions-permissions/monitor@v1
      with:
        config: ${{ vars.PERMISSIONS_CONFIG }}

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - uses: codelytv/pr-size-labeler@095a41fca88b8764fd9e008ad269bcdb82bb38b9 # v1.10.4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        xs_max_size: '10'
        s_max_size: '100'
        m_max_size: '500'
        l_max_size: '1000'
        fail_if_xl: 'false'
        # message_if_xl: 'This looks like a MAJOR change 😊'

    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        github_token: ${{ secrets.github_token }}
        labels: ${{ steps.size.outputs.stale_labels }}

    - uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.github_token }}
        labels: ${{ steps.size.outputs.new_label }}
